import type { Metadata } from "next";
import "./globals.css";

import { AdminContextProvider } from "@/context/AdminContextProvider";
import { CartContextProvider } from "@/context/CartContextProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "FAKE THOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
          <Header />
          <AdminContextProvider>
            <main>{children}</main>
          </AdminContextProvider>
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
